# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.56.0"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.hostname = "ubuntu"
  config.vm.synced_folder "../../Docker_Airflow_Postgres", "/home/vagrant/Docker_Airflow_Postgres"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", path: "bootstrap-root.sh"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4352"
  end
end
